apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: acrrepo
  namespace: ocihelm
spec:
  interval: 1m0s
  type: oci
  url: oci://fluxconfigtest.azurecr.io/helm
  provider: generic
